export const staticSuggestions = [
    "anomalies",
    "staff",
    "people",
    "temperature",
    "wind speed",
    "connection",
    "humidity",
    "battery",
    "energy",
    "reports",
    "solar panel",
    "robot",
    "maintenance",
    "alerts",
    "weather",
    "location",
    "efficiency",
    "production",
    "dashboard",
    "supervision",
    "map",
    "notifications",
    "admin",
    "user",
    "status",
    "mode",
    "speed",
    "panel",
    "damage",
    "dusty",
    "snow",
    "rain",
    "autonomous",
    "manual",
    "online",
    "offline",
    "fixed",
    "pending",
    "not fixed",
    "zone",
    "panel 1",
    "panel 2",
    "panel 3"
]; 